name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to GHCR
      uses: docker/login-action@v1.12.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push
      run: 
        |
        docker build . --file Dockerfile --tag ghcr.io/Lapis-lwy/code-server:latest
        docker push ghcr.io/Lapis-lwy/code-server:latest
      
      

      
