name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to GHCR
      uses: actions/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v2.7.0
      with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ghcr.io/Lapis-lwy/code-server:latest

      
